- name: Deploy donlocal-api to Kubernetes
  hosts: localhost
  connection: local
  tasks:
    - name: Apply Kubernetes manifest
      command: kubectl apply -f /mnt/c/ProgramData/Jenkins/.jenkins/workspace/donlocal-api-deploy-pipeline/deployment.yml