[master]
# control machine (this Ubuntu). use local connection so kubectl/kubeadm run here
localhost ansible_connection=local ansible_user=asaph

[workers]
# WSL worker IP (reported from WSL: hostname -I)
172.20.216.6 ansible_user=root ansible_port=22 ansible_ssh_private_key_file=~/.ssh/id_ed25519

[workers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
